# Generated by Django 4.0 on 2022-06-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sick_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdate', models.DateField()),
                ('tdate', models.DateField()),
                ('type_of_leave', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Annual Leave', 'Annual Leave')], default='', max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
