# Generated by Django 4.0.4 on 2022-06-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_leaveapp_authuser_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
